COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= fast_offset_compensation.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bma2.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk